### ISSUE TITLE
err required to be a Response object

### ISSUE THREAD

**Issue by charlierudolph** [Originate/response-state.coffee#2]
The example on the README always assumes the err is a `Response` object
I dislike this restriction as it requires the developer to wrap all errors other encountered (failed database transaction, filesystem error). Instead I would suggest the following:

```coffee
services.transferFunds from: 'checking', to: 'savings', amount: 100, (err, response) ->
  if err
    return send status: 500, message: 'please try again later'

  response.is
    success: -> send status: 201, message: "transfer created"
    unknown_account: -> send status: 400, message: 'unknown account given'
    insufficient_funds: -> send status: 403, message: 'not enough funds'
    limit_exceeded: -> send status: 403, message: 'daily transaction limit exceeded'
    unauthorized: -> send status: 401, message: 'please log in first'
```

Thus you always return a response object as the second parameter and never as an error.
`response.is` could throw if it has a status it doesn't know how to deal with. Thats definitely a different error and one where trying again later won't change anything.

**Comment by bentona** [comment]
As far as I understand it, it's the responsibility of a service fulfilling the ResponseState interface to wrap all possible responses. It might be ok to provide an `unknown_error` key to the response options, but having to check in two places for errors seems like it might lead to a lot of unnecessary complexity.

**Comment by kevgo** [comment]
Great suggestion! This is a question of how to apply the ResponseState pattern in Node, not so much the pattern itself. I can see that there are pros and cons for each of the discussed alternatives, and I'm not settled on one solution yet. Here are the pros and cons to each version from my perspective:

@kevgo proposal:
* pro: cleaner separation between error and success cases: errors states are all in the first parameter, success states all in the second. 
* pro: forces users to translate/wrap lower-level errors into higher-level errors. This makes sure that for example a service layer returns errors in the domain language of that layer ("no funds", "exceeded limit", "technical problems", etc, where applicable with lower-level errors wrapped)
* con: forces users to translate/wrap lower-level errors into higher-level errors. This can cause more boilerplate in API that want to expose "ResponseState a la @kevgo" APIs

@charlierudolph proposal:
* pro: all the ResponseState stuff is neatly in one place
* pro: simpler implementation of APIs that implement ResponseState
* con: two separate ways are necessary to distinguish and handle errors now: checking against an Error API, and then also against a Response API.
* kind of artificial and arbitrary separation of error types. Many domain-level errors can happen in subsystems, and would surface as "low-level" errors in the first callback parameter here, thereby leading to an API whose protocol is mostly determined by the way the API is implemented internally. Refactorings of those implementation details have an increased likelihood of public API changes as side effects in this scenario. To address this, we need intentional error mapping and dedicated boilerplate again.

In my opinion, this boils down to simpler client code (@kevgo) vs simpler API code (@charlierudolph). I'm leaning towards having clean, stable, and intentionally designed APIs, even if that means a bit more boilerplate sometimes. Keep in mind that these Response objects should only be created at functional boundaries (public APIs) of complex services, and not necessarily for every individual method. Also keep in mind that errors should be wrapped with descriptive higher-level messages anyways (https://www.joyent.com/developers/node/design/errors), thereby requiring boilerplate anyways for public APIs.

**Comment by kevgo** [comment]
Also see #3 for a way to reduce the boilerplate necessary to wrap `Error` into `Response`.

**Comment by charlierudolph** [comment]
If error needs to be a `Response` anyway, then why not just execute the callback with a single argument that is a `Response` returning two arguments? You could even remove the need for it being a callback.
```coffee
transferOptions = 
  from: 'checking'
  to: 'savings'
  amount: 100

responseCallbacks =
  success: (result) -> send status: 201, message: "transfer #{result} created"
  unknown_account: -> send status: 400, message: 'unknown account given'
  insufficient_funds: -> send status: 403, message: 'not enough funds'
  limit_exceeded: -> send status: 403, message: 'daily transaction limit exceeded'
  unauthorized: -> send status: 401, message: 'please log in first'
  other: -> send status: 500, message: 'please try again later'

services.transferFunds transferOptions, responseCallbacks
```

**Comment by kevgo** [comment]
That was the original idea, and its super close to the Ruby version. The reason I didn't go down this path is that its not backwards compatible to the Node.js way. If we agree that this isn't a requirement, this would indeed be much simpler and more elegant.

**Comment by kevgo** [comment]
See also discussion with @alexpeachey in #1.

**Comment by alexpeachey** [comment]
I'm definitely for just having a single arg in the callback as it's how the pattern was meant to be used. Also, the idea of passing an object full of labeled callbacks has good merit. In Ruby that would have been more cumbersome, but may make sense in Coffee. Either way I feel the caller of the service should not need to know what actually happened when calling the service. This can only be achieved by a single set of states/callbacks. If it's split over two, it kills a good part of the pattern.

**Comment by kevgo** [comment]
If we ditch backwards compatibility, then I like what @charlierudolph outlined above. I prefer the callback version, mostly because it provides the response object in a single place (we need the response object to get additional response data out of it), so it doesn't have to be introduced for each error handler. Also, it can be written pretty readable as a single block, without the need for temp variables.

```coffeescript
services.transferFunds from: 'checking', to: 'savings', amount: 100, (response) ->
  response.is
    success: -> send status: 201, message: "transfer #{response.txnId} created"
    unknown_account: -> send status: 400, message: 'unknown account given'
    insufficient_funds: -> send status: 403, message: "not enough funds, you have #{response.balance} left"
    limit_exceeded: -> send status: 403, message: "daily transaction limit of #{response.limit} exceeded"
    unauthorized: -> send status: 401, message: 'please log in first'
    other: -> send status: 500, message: 'please try again later' 
```

**Comment by charlierudolph** [comment]
Passing the response (or simply the data passed along with the state) and then destructing looks pretty nice to me.

```coffee
responseCallbacks = 
  success: ({txnId}) -> send status: 201, message: "transfer #{txnId} created"
  unknown_account: -> send status: 400, message: 'unknown account given'
  insufficient_funds: ({balance}) -> send status: 403, message: "not enough funds, you have #{balance} left"
  limit_exceeded: ({limit}) -> send status: 403, message: "daily transaction limit of #{limit} exceeded"
  unauthorized: -> send status: 401, message: 'please log in first'
  other: -> send status: 500, message: 'please try again later' 

services.transferFunds from: 'checking', to: 'savings', amount: 100, responseCallbacks
```

**Comment by kevgo** [comment]
Nice use of destructuring here! And yeah, this can work if we need only one or two elements. It will become a bit messy if there are more things returned, and it still requires the `responseCallbacks` temp variable, which defines the callback way before they are called, which messes up the control flow, though.

Another argument for the callback version is that we can do centralized things before taking apart the response, like logging:

```coffeescript
services.transferFunds from: 'checking', to: 'savings', amount: 100, (response) ->
  console.log "Received #{response} back from the service layer, after #{new Date() - start} ms"
  response.is
    success: -> send status: 201, message: "transfer #{response.txnId} created"
    # ....
```

Another advantage of making the response object available outside of the event handlers is that doing so allows us to distinguish synchronous from asynchronous event handlers. If all event handlers are synchronous, the `is` method could return the result from the event handler. This behavior would allow us to dry up this method into:

```coffeescript
services.transferFunds from: 'checking', to: 'savings', amount: 100, (response) ->
  [status, message] = response.is
    success: -> [201, "transfer #{response.txnId} created"]
    unknown_account: -> [400, 'unknown account given']
    insufficient_funds: -> [403, "not enough funds, you have #{response.balance} left"]
    limit_exceeded: -> [403, "daily transaction limit of #{response.limit} exceeded"]
    unauthorized: -> [401, 'please log in first']
    other: -> [500, 'please try again later']
  send {status, message}
```

**Comment by kevgo** [comment]
We can also just return the value from the given hash if it is not a function, further simplifying the code above to

```coffeescript
services.transferFunds from: 'checking', to: 'savings', amount: 100, (response) ->
  [status, message] = response.is
    success: [201, "transfer #{response.txnId} created"]
    unknown_account: [400, 'unknown account given']
    insufficient_funds: [403, "not enough funds, you have #{response.balance} left"]
    limit_exceeded: [403, "daily transaction limit of #{response.limit} exceeded"]
    unauthorized: [401, 'please log in first']
    other: [500, 'please try again later']
  send {status, message}
```

**Comment by kevgo** [comment]
After speaking with @alexdavid in person about this, I think we are all in agreement that a single response object is the better recommendation here. I have updated the readme accordingly. Please let me know what you think, and if you have better ideas, comments, or suggestions. This is coming together nicely!

**Comment by kevgo** [comment]
@charlierudolph Thanks for bringing this issue up. I think we came to a good solution. I'm closing this ticket for now, since there is no more `err` object. Feel free to reopen or create a new issue if there are other things you want to talk about here.
